/*
 * Smart 3D Mobile API
 * API for 3D printing service integration with advanced pricing logic.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CreateOrderPost200Response {
  
  @SerializedName("message")
  private String message = null;
  @SerializedName("order_id")
  private Integer orderId = null;
  @SerializedName("price")
  private BigDecimal price = null;
  @SerializedName("currency")
  private String currency = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOrderId() {
    return orderId;
  }
  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPrice() {
    return price;
  }
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateOrderPost200Response createOrderPost200Response = (CreateOrderPost200Response) o;
    return (this.message == null ? createOrderPost200Response.message == null : this.message.equals(createOrderPost200Response.message)) &&
        (this.orderId == null ? createOrderPost200Response.orderId == null : this.orderId.equals(createOrderPost200Response.orderId)) &&
        (this.price == null ? createOrderPost200Response.price == null : this.price.equals(createOrderPost200Response.price)) &&
        (this.currency == null ? createOrderPost200Response.currency == null : this.currency.equals(createOrderPost200Response.currency));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    result = 31 * result + (this.orderId == null ? 0: this.orderId.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateOrderPost200Response {\n");
    
    sb.append("  message: ").append(message).append("\n");
    sb.append("  orderId: ").append(orderId).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
